### ISSUE TITLE
The spec says "code point" where it likely means "unicode scalar value"

### ISSUE THREAD

**Issue by CAD97** [kdl-org/kdl#207]
From the [Unicode Glossary](https://unicode.org/glossary):
<blockquote>
<dl>
<dt><a href=https://unicode.org/glossary/#code_point>Code Point</a></dt>
<dd>(1) Any value in the Unicode codespace; that is, the range of integers from 0 to 10FFFF<sub>16</sub>. (See definition D10 in <a href=http://www.unicode.org/versions/latest/ch03.pdf#G2212>Section 3.4, Characters and Encoding</a>.) Not all code points are assigned to encoded characters. See <a href=https://unicode.org/glossary/#code_point_type>code point type</a>. (2) A value, or position, for a character, in any coded character set.</dd>
<dt><a href=https://unicode.org/glossary/#unicode_scalar_value>Unicode Scalar Value</a></dt>
<dd>Any Unicode <a href=https://unicode.org/glossary/#code_point>code point</a> except high-surrogate and low-surrogate code points. In other words, the ranges of integers 0 to D7FF<sub>16</sub> and E000<sub>16</sub> to 10FFFF<sub>16</sub> inclusive. (See definition D76 in <a href=http://www.unicode.org/versions/latest/ch03.pdf#G7404>Section 3.9, Unicode Encoding Forms</a>.)</dd>
</dl>
</blockquote>

The first requirement of the spec is that "KDL documents should be UTF-8". Similarly, strings "_MUST_ be represented as UTF-8 values." Note that a well-formed UTF-8 stream _MUST NOT_ contain surrogate code points; it encodes a sequence of USV.

However, the formal grammar just says `unicode` (presumably, either `[\0-\u{10FFFF}]` or `[\0-\u{D7FF}\u{E000}-\u{10FFFF}]` — unclear (#191, #192)), and the prose spec allows "literal code points" and escaped "Code point described by hex characters". This allows the presence of surrogates, at a minimum as escaped code points, even if their literal inclusion is precluded by the higher-level requirement that the document be well-formed UTF-8.

At least one implementation [documents this as a potential spec non-compliance](https://github.com/Lucretiel/kaydle/issues/8). Given the requirement of UTF-8, I expect that this is just a terminology oversight, and the spec should say Unicode Scalar Value (or non-surrogate code point) in the two locations where it currently just says "code point".

**Comment by tabatkins** [comment]
The former grammar referring to `unicode` as the set of all codepoints is fine, since valid UTF-8 documents can't encode the surrogate code points in the first place.

It's not *technically* necessary to restrict it from the unicode escape sequence either, tho it would complicated implementations by requiring them to store the values in something other than a UTF-8 string. So, I do recommend disallowing those code points, either by removing them from the escape's valid values, or allowing them but having those codepoints transform into U+FFFD REPLACEMENT CHARACTER. 

The latter is, for example, [what CSS does](https://drafts.csswg.org/css-syntax/#consume-escaped-code-point), but CSS has a requirement that all possible byte streams decode into *something*, while KDL is happy to reject entire documents that have a parse error. I don't have a strong opinion either way; it's generally an error to write such escapes in the first place.

**Comment by zkat** [comment]
This change is now included in the kdl-v2 branch.
