### ISSUE TITLE
Only one line continuation is allowed by formal grammar

### ISSUE THREAD

**Issue by CAD97** [kdl-org/kdl#254]
```
node-space := ws* escline ws* | ws+
escline := '\\' ws* (single-line-comment | newline)
```

If this is intended, it should probably be noted in [the prose part of the spec](https://github.com/kdl-org/kdl/blob/main/SPEC.md#line-continuation).

If multiple line continuations should be allowed, then this adjustment should be sufficient:

```
node-space := ws* (escline ws*)+ | ws+
```

Example previously invalid but made valid document:

```
node 1 2 \ // I don't know why you would want to do this
         \ // but I think you should be allowed to do it
     3 4   // and see no non-formal reason to forbid it.
```

**Comment by spaarmann** [comment]
I'm not super familiar with reading grammars, so apologies if I'm missing something, but: `node-space` only appears in the grammar as `node-space+` or `node-space*`. If I'm understanding it correctly, that means that effectively multiple line continuations are allowed everywhere, because multiple `node-space`s are.
