### ISSUE TITLE
Line continuations can be terminated with EOF only when a comment is present

### ISSUE THREAD

**Issue by Bannerets** [kdl-org/kdl#337]
I thought this was already reported, but I can't seem to find any issue/discussion, so I'm opening a new one.

Right now, the line continuation is defined as
```bnf
escline := '\\' ws* (single-line-comment | newline)
```

Where `single-line-comment` is (includes eof):
```bnf
single-line-comment := '//' ^newline* (newline | eof)
```

This means that `node \ // comment <EOF>` is allowed as the last line, but `node \ <EOF>` is not, which feels weird. I think `escline` should probably include `eof` as well.

**Comment by Patitotective** [comment]
As far as I understand the line continuations breaks a node, let's say:
```
node 1 2 \
     3 4
```
So you can't really put nothing (or end the file) after `\`, that's why it expects a new line.
Just like the KDL below is invalid, ending a file after a line continuation is invalid.
```
node 1 2 \
node
```
Instead a single line comment CAN end a file since it's not really part of a node, and it's not breaking a node.

Or at least that's why I understood from the specification :sweat_smile:.

**Comment by zkat** [comment]
probably what we want is something like `(single-line-comment eof? | newline)`

**Comment by zkat** [comment]
This has been merged into the kdl-v2 branch
