### ISSUE TITLE
KDL 2.0: prefix keywords with  `#`

### ISSUE THREAD

**Issue by zkat** [kdl-org/kdl#343]
I propose we remove the `true`, `false`, and `null` tokens, ban `#` from identifiers, and then add `#true`, `#false`, and `#null` to replace them.

This would essentially remove any ambiguity issues from implementing #339.

It also creates a handy namespace for future keywords, if there's ever a KDL 3.0 or 2.x draft.

**Comment by dezren39** [comment]
initially this felt bad, but i came around to this. namespaces are always handy. i can already see some peoples first introduction to kdl being a config file that happens to be filled with a ton of "#true #false" in a row and being like 'wtf?' but that is probably ok. would this be ban # from identifiers or add it to the 'not allowed as the first character' list?
![image](https://github.com/kdl-org/kdl/assets/11225574/62d64e95-a336-4541-83bf-c21eca7dc6f9)

**Comment by zkat** [comment]
My intention was to ban `#` altogether.

**Comment by larsgw** [comment]
It's a bit weird but I think I still prefer to distinguish keywords from strings syntactically. So if we remove the specific syntax for (some) strings, I think it makes sense to introduce specific syntax for keywords.

**Comment by zkat** [comment]
random thought: does this mean that we could also remove the `r` prefix from `r#` raw strings, and just make raw strings be `#"foo"`?

**Comment by MultisampledNight** [comment]
This makes me think a bit of [typst](https://typst.app), where there's basically 2 (or 3 if one counts math) languages in one. The default one is _markup_, where text mostly appears as it is written, with some syntax sugar for highlighting, lists and the like.

However, using `#`, one can switch to code mode: The block or statement following the `#` is interpreted in a custom scripting language.

For typst, that decision makes sense since most of the actual document is written in markup (and one can switch from code mode back to markup mode using `[]` brackets).

For kdl, I'm not entirely sure. There's no full-blown scripting language behind the scenes, but I believe the basic reasoning works the same as it does for typst: Most documents written in kdl probably aren't just accumulations of true/false/null switches, but perhaps more expressive.

**Comment by larsgw** [comment]
(hey, typst mention, nice!)

**Comment by tabatkins** [comment]
> random thought: does this mean that we could also remove the r prefix

That seems to be an independent decision, yeah? The fact that #-strings and raw-strings are tied together right now actually feels slightly weird - #-strings let you safely use quotes in your string, while raw strings let you safely use `\` in your string.

**Comment by zkat** [comment]
Withdrawing this proposal because I hate it, actually.
