### ISSUE TITLE
KDL 2.0: #-prefixed up-to-EOL/EOF strings

### ISSUE THREAD

**Issue by zkat** [kdl-org/kdl#357]
A notable KDL user proposed the following, and I really like the idea, especially as an alternative to #350!

See https://hachyderm.io/@imsnif/111562960286972816

The proposal is to make it so `#` (or any number of them together) initiate a raw string that terminates at the next EOL/EOF. It would follow the same rules as raw strings for escaping multiple `#`s in it, but would not require a closing `#`, unlike `#""#` strings.

For example:

```kdl
action {
  cmd #cargo run -- C:\foo\bar.txt
  env foo=1 bar=##something with a # in it
}
```

**Comment by imsnif** [comment]
Hey, just to say more about my use case:

Right now we use KDL both for configuration and serialization in Zellij. We serialize for example our application state. I absolutely love the fact that KDL allows for a Human readable serialization format.

The only part of our state which we don't serialize to KDL right now is the terminal viewport/scrollback. We use raw ANSI for this, and well... raw ANSI is great, but it can't be accused of being Human readable.

I'd very much like to be able to do something like this (abridged for brevity's sake):
```kdl
#Welcome to fish, the friendly interactive shell
#Type help for instructions on how to use fish
"aram@" foreground "#86DC3D" "green" #~/> cd /tmp
"aram@" foreground "#86DC3D" "green" #/tmp> ls -l
#drwx------    - aram  8 Dec 22:09 v5vdLzt
#drwx------    - aram  8 Dec 22:09 v8etVMk
#drwx------    - aram  7 Dec 23:53 vCDeNFk
#drwx------    - aram  8 Dec 22:09 veIczLl
#drwx------    - aram  8 Dec 22:09 vJN15f5
"aram@" foreground "#86DC3D" "green" #/tmp>
```

Instead of something like this screenshot:

![img-2023-12-11-185104](https://github.com/kdl-org/kdl/assets/795598/9dc1b42d-cbe5-47da-8e20-26d4bde3d47b)

**Comment by tabatkins** [comment]
I'm not nearly as much a fan of this, at least not using this syntax.

The use-case presented appears to be actually leaning much closer to SDLang's "anonymous nodes", where *only* attributes are given and the node name is omitted. It happens to be written in such a way that the processor can just treat every node's name as being another string attribute. These would all be better fit into KDL if written as actual nodes with a bunch of string attributes, even as minimal as a `*` node.

(I'm also not sure how that example would work - the `foreground` bits aren't marked as strings at all. I presume this is giving the foreground color as both a hex color and a color name? It looks like the implicit format is output strings, separated by three strings giving color information. Is that right? How do you set both foreground and background?)

Given that the first string on most of the lines (the `"aram@"` part) is okay to be quoted, I'm not sure I see why the other output strings aren't acceptable to be quoted. Similarly, the "til end of line" behavior means that if you *did* want to add more formatting, you'd have to go back and rewrite the final string to use quoted form, so you can follow it up with something else.

In other words, I think I might write the above example like:

```kdl
line "Welcome to fish, the friendly interactive shell"
line "Type help for instructions on how to use fish"
line "aram@" (fg)"#86DC3D green" "~/> cd /tmp"
line "aram@" (fg)"#86DC3D green" "/tmp> ls -l"
line "drwx------    - aram  8 Dec 22:09 v5vdLzt"
line "drwx------    - aram  8 Dec 22:09 v8etVMk"
line "drwx------    - aram  7 Dec 23:53 vCDeNFk"
line "drwx------    - aram  8 Dec 22:09 veIczLl"
line "drwx------    - aram  8 Dec 22:09 vJN15f5"
line "aram@" (fg)"#86DC3D green" "/tmp>"
```

That is, nodes for each line, containing attributes that are either content strings (text to print) or `(fg)` or `(bg)`-tagged strings that change the format of the following content strings. This feels pretty human-readable to me, and is still just a pretty straightforward translation of the ANSI formatting.

--------

Ignoring this use-case in particular, tho, this proposal doesn't address the "I want to use a bunch of unquoted words as strings in my nodes" use-case that we were trying to solve in the first place. It also ends up looking a *lot* like a comment syntax, since several config languages, and Python, use `#` to start a "rest of line" comment.

**Comment by zkat** [comment]
closing this. It looks like we're gonna go with #339 after all
