### ISSUE TITLE
How do i refer to the properties of another node?

### ISSUE THREAD

**Issue by hallonfras** [kdl-org/kdl#404]
Hi! Im using a WM which config file is written in KDL.

IF possible i would like to have a node

colors green="blue" black="White"

and be able to refer to these somewhere else in the config file.

I would also like to ask if it is possible to import the contents of another KDL file somehow?

**Comment by zkat** [comment]
I assume you're using Niri?

KDL itself intentionally does not include any self-referencing or importing facilities, since that would significantly complicate implementation. Instead, the expectation is that any behavior like this be done at the application level.

So, if Niri wants to add referrable nodes, it can do so somewhat easily, in a way that makes sense for niri in particular.
