### ISSUE TITLE
[v2] Should triple-quoted strings be allowed to contain unescaped quotes?

### ISSUE THREAD

**Issue by tjol** [kdl-org/kdl#415]
I rather like the new multi-line string syntax (#413). It's elegant, it's familiar, it fixes a thing we were worried about, but — it raises a question:

```
"""
is "this"
a valid string?
"""
```

The draft spec says no right now, but there's really no reason not to allow `"` characters in a triple-`"` string (as long as there aren't three in a row). Plus, Python allows it.

**Comment by zkat** [comment]
I thought about this, and my initial inclination was "keep the exact same rules for strings, besides the specific newline rules". I do like the idea, though.

What would you expect this to look like for multiline raw strings?

**Comment by tjol** [comment]
Raw strings already allow quotes in the middle, so there's less potential for a surprise there either way.

My first thought was that if a multi-line raw string literal  starts with `##"""`, then it ends with the next `"""##`, and everything in between is part of the string. 

Let's consider this pathological example:

```
#"""a"# b #"c"""#
```

I see three options:
 1. This is one string: `"a\"# b #\"c"` (i.e. `##"a"# b #"c"##`)
 2. This is an error: multi-line raw string `#"""a"#` ended with a single quotation mark
 3. There are no multi-line strings here at all and this is equivalent to `"\"\"a" b "c\"\""`

I'd tend towards option 1 here. I'm actually not sure whether the current draft technically favours 2 or 3.

**Comment by tabatkins** [comment]
Yeah, I kinda expected the new triple-quote strings to go with "the same rules as normal strings", where "the same" meant "can't put the closing delimiter inside", not "can't put `"` inside".

> `#"""a"# b #"c"""#`

This isn't a valid multiline string; you have to follow the opener with a newline. (It's not a valid single-line string, either, since `"""` always indicates a multi-line.)

**Comment by tjol** [comment]
Ah, of course, the newline rule would appear to sort out the ambiguity problem I was concerned about.

**Comment by zkat** [comment]
I think what I'm thinking of is also the grammar: this rule is easy enough to apply to regular quoted strings, grammar-wise, because you just say that for multiline strings, you can do string-chars or one or two consecutive `"`, but for raw multiliners you have to take into account the `###` prefixes and it's totally doable I just feel lazy about updating the grammar for it.

@tjol would you be up to setting up a PR with the proposed grammar changes, at least? I can help with the prose if you want.

**Comment by tjol** [comment]
I'll give it a go.

**Comment by tabatkins** [comment]
Reopening now that I'm implementing these, as I think the new rules might still be too restrictive.

As best as I can interpret the grammar, a raw multiline string can contain as many quotes as it wants, and even contain a correct closing sequence of triple-quotes-and-the-right-number-of-hashes, as long as that sequence doesn't appear *as the first non-whitespact content on the line*.

That is, by my read this is valid:

```kdl
node #"""
  foo """#
  """#
```

And results in the same value as `node "foo \"\"\"#"`.

Assuming this is correct, I don't understand why this shouldn't equally apply to non-raw multiline strings, so that this is valid too:

```kdl
node """
  foo """
  """
```

Per the current spec, tho, non-raw multiline strings are disallowed from containing three quotes in a row no matter their position, despite them being equally "not the closing quotes" as in the raw string example. In my current implementation, that'll require adding a special case solely for catching this error in non-raw strings.

(Alternately, I'm reading the grammar wrong and the raw-multiline case should be invalid as well.)

**Comment by zkat** [comment]
I think neither of those should be legal: I think we should absolutely get an error about the last line in a multiline string not being whitespace-only before the closer. So we should probably fix the raw-string grammar.

**Comment by tabatkins** [comment]
Okay.

I'm not certain this *can* be compactly expressed in the grammar form; it might need to be a condition imposed on top of the parsing.

**Comment by zkat** [comment]
We could just apply the exact same rule as the regular multiline strings, and make it so this is illegal:

```kdl
foo #"""
  """
  """#
```

It's better than slapping a higher level thing or making the grammar super complex.

**Comment by tabatkins** [comment]
No, that would be a bad idea - it defeats one of the points of raw strings, where you can put *anything* inside of them as long as you slap enough #s around it (which is good, since you can't escape your way out of it). We definitely should still only end the string when we see `"""` with equal or more `#` than it started with.

**Comment by zkat** [comment]
yeah, but i'm worried about adding a level of complexity to the grammar that would make it hard for e.g. parser generators to handle without additional logic, such as treesitter or textmate/tmlanguage. I'm not sure we could have those check for `"""<number of opening '#'s`?

**Comment by tabatkins** [comment]
I sympathize, but I think that quality of raw strings is *really* important for them. Without it, it means that multiline strings are simple *incapable* of containing `"""`, while single-line raw strings can do it no problem as long as it's not at the start; that seems weird and bad.

...actually, reading the grammar again, single-line raw strings don't actually correctly impose their requirement either, so we can't actually lean on them. They disallow themselves from *starting* with three quotes, but once you pass that check they can contain almost any characters at all, including the correct ending sequence, so long as the correct ending sequence appears *somewhere* later in the document.

So both types of raw strings actually need a stronger grammar requirement than what can be cleanly expressed.

**Comment by tabatkins** [comment]
Specifically, per the grammar `single-line-raw-string-char` is totally allowed to expand into `"#` if it wants, even in the string starts with `#"`, as long as at some point later in the document `raw_string` can consume another `"#` to end itself with.

**Comment by zkat** [comment]
I guess this depends on the parser, actually. An eager parser will end the string parse as soon as it hits a `"""#`, and then decide that's an error. And I kind of agree with that behavior. Likewise, plain `"""` for multiline quoteds.

**Comment by tabatkins** [comment]
Right, I think that's the *right* behavior; what I'm saying is that the grammar is ambiguous and allows the other behavior as written.

We don't have a specific requirement that the grammar's multipliers are either greedy or non-greedy, so I'll assume they're allowed to take any value that eventually results in a valid document parse, but if they rely on greedy multipliers as usual, then the bad behavior is in fact what you'll get from a generated parser.

**Comment by zkat** [comment]
So you're saying we should leave it as-is, and make it so the `foo """#` example is legal?

**Comment by tabatkins** [comment]
No, I think it's probably best to make `foo """#` illegal - it's the most consistent behavior overall.

We should express the raw-string "matching #" ending requirement as a higher-level constraint on the grammar, for both single-line and multi-line raw strings - their `-raw-string-body` constructions have an additional requirement that they're not allowed to contain the valid closing sequence.

**Comment by tabatkins** [comment]
With this addition, then:

```kdl
single #"foo"#"#

multi #"""
  foo"""#
  """#
```

`single` would be required to end the string at the first `"#` (as otherwise the string body would contain the valid ending sequence), an then the following `"#` will fail to parse as anything.

`double` would simply not parse as a multi-line at all; it can't parse past the `foo"""#` (as that would cause the string body to contain the valid ending sequence), but it's not allowed to end at that point either, since there's preceding non-whitespace characters. So the whole attempt to parse as a string fails (it already failed to be a single-line raw string, since it has three starting quotes) and it can't parse as anything else, so it's a parse failure overall.

**Comment by zkat** [comment]
fwiw this is how Rust defines its raw strings:

```
    Lexer
    RAW_STRING_LITERAL :
       r RAW_STRING_CONTENT SUFFIX?

    RAW_STRING_CONTENT :
          " ( ~ IsolatedCR )* (non-greedy) "
       | # RAW_STRING_CONTENT #
```

So maybe what we need is specifically a grammar extension to allow the `(non-greedy)` modifier?

**Comment by zkat** [comment]
I believe both tmlanguage and treesitter would support `(non-greedy)` ootb, too.

**Comment by tabatkins** [comment]
It has to be non-greedy *and infallible*, I think. If still fallible, then while you'll try to end the string at the first instance of the ending sequence, if that results in a bad parse you'll just keep on trucking and see if you can go further.

Note that this would require us to drop the part of the grammar that specifies multiline strings end with just whitespace; we'll need to instead impose that requirement on top (like we already do with the requirement that all the lines have the same ws prefix). That is, we'd need to switch to:

```
current:
raw-string-quotes := '"' single-line-raw-string-body '"' | '"""' newline multi-line-raw-string-body newline unicode-space* '"""'
new:
raw-string-quotes := '"' single-line-raw-string-body '"' | '"""' newline multi-line-raw-string-body '"""'
```

**Comment by zkat** [comment]
We can add those modifiers, I guess :) I'd be happy with that grammar change.

**Comment by tabatkins** [comment]
k, wanna just go with the standard `*?` spelling for a non-greedy star?

**Comment by zkat** [comment]
@tabatkins yeah, as long as we add that to the grammar language documentation on the bottom.
