### ISSUE TITLE
Slashdash, per grammar, doesn't allow an escaped newline after it

### ISSUE THREAD

**Issue by tabatkins** [kdl-org/kdl#426]
Per the current grammar, the test `slashdash_arg_before_newline_esc.kdl` contains a parse error.

```kdl
node /-    \
    arg
```

Notably, slashdash allows `line-space` at its end, which does *not* include `escline`. The escaped newlines is allowed *before* the slashdash or *after* the attribute (since then it would be part of the allowed `node-space`), but not between the slashdash and the attribute.

Given that this test is intended-successful, I suspect it's intended that a slashdash allow `node-space` after itself too. Does this sound correct?

**Comment by zkat** [comment]
oh. huh.

I was curious as to why `kdl-rs` wasn't failing this test, and it's because... yeah, [I'm effectively putting a `node-space*` before every `node-entry`](https://github.com/kdl-org/kdl-rs/blob/main/src/v2_parser.rs#L418-L440)

So yeah, `slashdash := '/-' (node-space | line-space)*` seems like a good patch. I'm surprised no one else has run into it either, but I assume that's a function of how new this change is, and how... realistically, most parsers would also allow `node-space*` before node entries.

**Comment by Alch-Emi** [comment]
Maybe this isn't intended behavior, but shouldn't this be allowed under the current (75a0869) grammar?

The entries part of the spec is:

```ebnf
node := ... (node-space+ slashdash? node-prop-or-arg)* ...
```

and `node-prop-or-arg` is

```ebnf
node-prop-or-arg := prop | value
value := type? node-space* (string | number | keyword)
```

So if `type?` is `""` and `node-prop-or-arg` is `value`, then the collapsed expression should look like:

```ebnf
node := ... (node-space+ slashdash? node-space* (string | number | keyword))* ...
```

Which does permit `node-space` after the `slashdash`, even if it's not the `linespace` that's directly associated with the `slashdash`.

**Comment by zkat** [comment]
@Alch-Emi ahh good catch. Yeah. Having it only work when you don't have a type annotation is supremely weird lol

anyway this is pretty minor. I'll PR it and probably self-merge.

**Comment by tabatkins** [comment]
@Alch-Emi oh lol nice catch, that means I'm doing something wrong still
