### ISSUE TITLE
Add a logo for KDL

### ISSUE THREAD

**Issue by obeid** [kdl-org/kdl#46]
KDL does not _need_ a logo, but as an early fan, I _want_ it to have a logo.

**Comment by timmybytes** [comment]
I did a quick little mock-up of a logo, pretty heavily emphasizing the "cuddly" feel of the KDL name in case you're interested @zkat? It has a transparent background, so it works with light and dark backgrounds.

![KDL_Logo_Draft](https://user-images.githubusercontent.com/67444371/103307922-0ae40500-49c6-11eb-8506-03c7e7667329.png)

If you like it I can submit a PR, or if you have suggestions I can work on different versions!

**Comment by zkat** [comment]
Um, I actually _love_ this? It is extremely my kind of vibe. I'm wondering what others think, too? Because in my mind, we'd just adopt this right now hahah.

**Comment by obeid** [comment]
I made the issue so I can design the logo, but I wouldn't be mad if this gets used. I'm feeling it too. Great job @timmybytes

**Comment by timmybytes** [comment]
Oh sorry, @obeid! I didn't mean to step on any toes, I just geek out on designing these kinds of things. But I'm so glad you and @zkat like it! I'll tweak a couple things to get the design a little more polished, and make some different versions for various use cases (repo sharing card, svg, logo without tagline, etc.) if that's okay?

**Comment by Rupertofly** [comment]
Ah, the slippery slope of branding, if we use it, could you let us know the colours and font used?

**Comment by timmybytes** [comment]
The font is [Nunito](https://fonts.google.com/specimen/Nunito), an Open Font licensed Google Font. I made six different sizing variations (though I'm having issues with exporting to SVG), and included a simple styles sheet (shown here as a PNG since I can't attach the PDF). While the "Medium" and "Large" sized canvases are the same size, the medium has more empty space for breathing room. No worries at all if you all end up going with something different. If anything, it was fun to practice with!

![Styles](https://user-images.githubusercontent.com/67444371/103321690-bd7c8d80-49ef-11eb-9451-aa2800d8d4d4.png)
![KDL_Logo_Only_Large_1280x640](https://user-images.githubusercontent.com/67444371/103321700-c4a39b80-49ef-11eb-8791-721df6aaf7da.png)
Large 1280x640 Logo

![KDL_Logo_Only_Medium_1280x640](https://user-images.githubusercontent.com/67444371/103321703-c9684f80-49ef-11eb-88b8-f309d8cd5fad.png)
Medium 1280x640 Logo

![KDL_Logo_Only_Small_512x512](https://user-images.githubusercontent.com/67444371/103321706-cc634000-49ef-11eb-910b-36518e4321c9.png)
Small 512x512 Logo

![KDL_Logo_with_Tagline_Large_1280x640](https://user-images.githubusercontent.com/67444371/103321709-ce2d0380-49ef-11eb-81fe-82df62acf8cf.png)
Large 1280x640 Logo w/Tagline

![KDL_Logo_with_Tagline_Medium_1280x640](https://user-images.githubusercontent.com/67444371/103321712-d08f5d80-49ef-11eb-90d6-b958568b5ed9.png)
Medium 1280x640 Logo w/Tagline

![KDL_Logo_with_Tagline_Small_512x512](https://user-images.githubusercontent.com/67444371/103321713-d2f1b780-49ef-11eb-93c8-63ecfc29c36e.png)
Small 512x512 Logo w/Tagline

**Comment by zkat** [comment]
@timmybytes thinking about this more... I actually really like this! I really appreciate the time you put into this. I really like going for the "cuddly" vibe, making things more feminine because... you don't see that very often.

At the same time, I wonder if it's too _young_? Like, is this something that would be more reminiscent of branding for children? It's not a bad vibe, but I'm also wondering if there's a way to take this design and make it more "playful" and less "child"? What do you think?

**Comment by zkat** [comment]
Actually, giving more concrete feedback: what would this look like if the letters were straight, instead of shifted? Even if they overlap a little, idk? I'm just spitballing here. I've been staring at this logo and trying to put my finger on what I would want to change haha

**Comment by timmybytes** [comment]
Yeah, I was wondering the same thing actually. I think that kind of connotation could be avoided more by altering the color scheme, or switching to a single color for the “KDL” bit. I’ve got some other projects to get to today, but I’ll do some more mock-ups (including straightened letters), and add more here when I have them!

**Comment by zkat** [comment]
aaah awesome. Thank you so much! I'm v excited :)

**Comment by timmybytes** [comment]
My pleasure!

**Comment by obeid** [comment]
![kdl_mono](https://user-images.githubusercontent.com/3066028/103323428-c762b880-4a10-11eb-9053-cdf0d788234a.png)

Inspired by the great work @timmybytes put into this. I created three original monospaced glyphs of 'KDL' with the same rounded corners and colors and kept them aligned. Thoughts?

**Comment by obeid** [comment]
<img width="744" alt="Screen Shot 2020-12-29 at 8 08 10 PM" src="https://user-images.githubusercontent.com/3066028/103323593-98007b80-4a11-11eb-88dc-f714792b1750.png">
OMG I just realized what @zkat wanted to achieve with the overlap. THEY ARE CUDDLING!

**Comment by obeid** [comment]
![kuddle](https://user-images.githubusercontent.com/3066028/103324165-2a098380-4a14-11eb-8c8c-4e6ea8ba8e20.png)
Leaning into the 'Kuddle' idea.

**Comment by obeid** [comment]
![kuddle_corrected](https://user-images.githubusercontent.com/3066028/103324303-efecb180-4a14-11eb-8cce-bd53839d5333.png)
Fixed the K from the last one.

**Comment by obeid** [comment]
![dic](https://user-images.githubusercontent.com/3066028/103330118-1a973400-4a2e-11eb-9813-0645c1e3b464.png)
One last concept and I will go to bed.

**Comment by timmybytes** [comment]
Ok here's a more muted version that still feels a bit playful. I added a drop shadow too that adds some depth with the thick outline stroke and it feels a bit "heavier" now.

![Tagline Large 1280x640](https://user-images.githubusercontent.com/67444371/103367951-34129d00-4a7b-11eb-8e0e-b30375ed29b9.png)

I've made mock-ups of lots of other versions, however, and while there are too many to just tack on here, you can view them all on my Figma file here: https://www.figma.com/file/IoyVCJr059RZEHEfEKROPt/KDL-Logo?node-id=11%3A936

Let me know if anything jumps out at you!

**Comment by obeid** [comment]
![Asset 8@16x](https://user-images.githubusercontent.com/3066028/103369040-1e12d580-4a97-11eb-99d4-16d8ce0702c4.png)
This where am at with this option. Added soft shadows and a monochrome version.

**Comment by jellymann** [comment]
I think it needs some cats incorporated somewhere

**Comment by zkat** [comment]
@timmybytes I spent some time thinking about it, looked at it again, looked at all the alternatives you so kindly put together, and I think my favorite is your original at https://github.com/kdl-org/kdl/issues/46#issuecomment-752282368

Can we go with that one

**Comment by timmybytes** [comment]
@zkat Absolutely! I’ll submit a PR that includes a directory for the graphics files, and maybe pop one of the images into the PR’s README so you can see how it would be displayed? I’m also adding favicons to the batch in case you ever want to set up a dedicated site for KDL.

**Comment by zkat** [comment]
We actually already have a dedicated site over at https://github.com/kdl-org/kdl-org.github.io (https://kdl.dev)!

**Comment by timmybytes** [comment]
Oh awesome, I missed that! It looks great!

**Comment by zkat** [comment]
Gonna close this because #61
